/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.tudarmstadt.esa.treenail;

import com.google.inject.Inject;
import com.google.inject.Provider;
import com.minres.coredsl.CoreDslStandaloneSetup;
import com.minres.coredsl.coreDsl.DescriptionContent;
import de.tudarmstadt.esa.treenail.codegen.LongnailCodegen;
import java.io.FileWriter;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.HelpFormatter;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.ParseException;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.xtext.diagnostics.Severity;
import org.eclipse.xtext.generator.JavaIoFileSystemAccess;
import org.eclipse.xtext.util.CancelIndicator;
import org.eclipse.xtext.validation.CheckMode;
import org.eclipse.xtext.validation.IResourceValidator;

public class App {
  @Inject Provider<ResourceSet> resourceSetProvider;
  @Inject IResourceValidator validator;
  @Inject JavaIoFileSystemAccess fileAccess;

  public DescriptionContent parse(String fileName) {
    var resourceSet = resourceSetProvider.get();
    var resource = resourceSet.getResource(URI.createFileURI(fileName), true);
    var issues =
        validator.validate(resource, CheckMode.ALL, CancelIndicator.NullImpl);

    if (issues.stream().anyMatch(i -> i.getSeverity() == Severity.ERROR)) {
      System.err.println("Parsing failed:");
      issues.forEach(System.err::println);
      return null;
    }

    return (DescriptionContent)resource.getContents().get(0);
  }

  public String generateMLIR(DescriptionContent content) {
    var codegen = new LongnailCodegen();
    return codegen.emit(content);
  }

  public static App getInstance() {
    var injector =
        new CoreDslStandaloneSetup().createInjectorAndDoEMFRegistration();
    return injector.getInstance(App.class);
  }

  private static Options createOptions() {
    var options = new Options();

    options.addOption(
        Option.builder("o")
            .longOpt("out")
            .argName("output file")
            .hasArg()
            .required(false)
            .desc("file to store the emitted MLIR code for Longnail")
            .build());
    options.addOption(Option.builder("h")
                          .longOpt("help")
                          .required(false)
                          .desc("Print this message")
                          .build());

    return options;
  }

  private static void printHelp(Options options) {
    new HelpFormatter().printHelp("treenail <ISAX>.core_desc [options]",
                                  options);
  }

  public static void main(String[] args) {
    var options = createOptions();
    String coreDescPath = null;
    String mlirOutPath = null;
    try {
      var cmd = new DefaultParser().parse(options, args);
      if (cmd.hasOption("h")) {
        printHelp(options);
        System.exit(0);
      }

      String[] remainingArgs = cmd.getArgs();
      if (remainingArgs.length != 1) {
        System.err.println("ERROR: Missing CoreDSL ISAX description file!");
        printHelp(options);
        System.exit(-1);
      }

      coreDescPath = remainingArgs[0];
      mlirOutPath = cmd.getOptionValue("o");
    } catch (ParseException e) {
      System.err.println(e.getMessage());
      printHelp(options);
      System.exit(1);
    }

    var app = getInstance();
    var content = app.parse(coreDescPath);
    if (content == null)
      System.exit(3);

    var mlir = app.generateMLIR(content);
    if (mlir == null)
      System.exit(4);

    if (mlirOutPath != null) {
      try {
        var w = new FileWriter(mlirOutPath);
        w.write(mlir);
        w.close();
      } catch (Exception e) {
        e.printStackTrace();
        System.exit(5);
      }
      return;
    }

    System.out.println(mlir);
  }
}
