/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.tudarmstadt.esa.treenail;

import com.google.inject.Inject;
import com.google.inject.Provider;
import com.minres.coredsl.CoreDslStandaloneSetup;
import com.minres.coredsl.coreDsl.DescriptionContent;
import de.tudarmstadt.esa.treenail.codegen.LongnailCodegen;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.xtext.diagnostics.Severity;
import org.eclipse.xtext.generator.JavaIoFileSystemAccess;
import org.eclipse.xtext.util.CancelIndicator;
import org.eclipse.xtext.validation.CheckMode;
import org.eclipse.xtext.validation.IResourceValidator;

public class App {
  @Inject Provider<ResourceSet> resourceSetProvider;
  @Inject IResourceValidator validator;
  @Inject JavaIoFileSystemAccess fileAccess;

  public DescriptionContent parse(String fileName) {
    var resourceSet = resourceSetProvider.get();
    var resource = resourceSet.getResource(URI.createFileURI(fileName), true);
    var issues =
        validator.validate(resource, CheckMode.ALL, CancelIndicator.NullImpl);

    if (!issues.isEmpty() &&
        issues.stream().anyMatch(i -> i.getSeverity() != Severity.INFO)) {
      System.err.println("Parsing failed:");
      issues.forEach(System.err::println);
      return null;
    }

    return (DescriptionContent)resource.getContents().get(0);
  }

  public String generateMLIR(DescriptionContent content) {
    var codegen = new LongnailCodegen();
    return codegen.emit(content);
  }

  public static App getInstance() {
    var injector =
        new CoreDslStandaloneSetup().createInjectorAndDoEMFRegistration();
    return injector.getInstance(App.class);
  }

  public static void main(String[] args) {
    assert args.length > 0;
    var app = getInstance();
    var content = app.parse(args[0]);
    if (content != null)
      System.out.println(app.generateMLIR(content));
  }
}
