/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.tudarmstadt.esa.treenail;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  void parserWorks() {
    var appInst = App.getInstance();
    var fileName = getClass().getResource("intro_syntax.core_desc").getPath();
    assertTrue(appInst.parse(fileName),
               "app should be able to parse a simple CoreDSL file");
  }
}
