/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.tudarmstadt.esa.treenail;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  void parserWorks() {
    var appInst = App.getInstance();
    var fileName = getClass().getResource("intro_syntax.core_desc").getPath();
    assertNotNull(appInst.parse(fileName),
                  "app should be able to parse a simple CoreDSL file");
  }

  @Test
  void codegenWorks() {
    var appInst = App.getInstance();
    var fileName = getClass().getResource("test1.core_desc").getPath();
    var content = appInst.parse(fileName);
    assertNotNull(content, "app should be able to parse a simple CoreDSL file");
    assertTrue(
        appInst.generateMLIR(content).startsWith("coredsl.isax \"Test1\""),
        "app should be able to generate MLIR");
  }

  @Test
  void splitEncodingFieldWorks() {
    var appInst = App.getInstance();
    var fileName =
        getClass().getResource("split_enc_field.core_desc").getPath();
    var content = appInst.parse(fileName);
    var mlirCode = appInst.generateMLIR(content);
    assertNotNull(content, "app should be able to parse a simple CoreDSL file");
    assertTrue(mlirCode.startsWith("coredsl.isax \"TestSplitEncFields\""),
               "app should be able to generate MLIR");
    assertTrue(mlirCode.contains("%TREENAIL_WAS_HERE_0 = coredsl.concat "
                                 + "%TREENAIL_WAS_HERE_Imm6_5_1, "
                                 + "%TREENAIL_WAS_HERE_Imm6_0_0 : ui5, ui1"),
               "app should be able to merge split encoding fields");
    assertTrue(
        mlirCode.contains(
            "%Imm6 = coredsl.cast %TREENAIL_WAS_HERE_0 : ui6 to ui6"),
        "app should be able to retain the original split encoding field name");
  }

  @Test
  void reversedEncodingFieldWorks() {
    var appInst = App.getInstance();
    var fileName =
        getClass().getResource("reversed_enc_field.core_desc").getPath();
    var content = appInst.parse(fileName);
    var mlirCode = appInst.generateMLIR(content);
    assertNotNull(content, "app should be able to parse a simple CoreDSL file");
    assertTrue(mlirCode.startsWith("coredsl.isax \"TestReversedEncFields\""),
               "app should be able to generate MLIR");
    assertTrue(
        mlirCode.contains("%TREENAIL_WAS_HERE_reversed_0 = coredsl.bitextract "
                          + "%TREENAIL_WAS_HERE_Imm6_5_0[0:5] : (ui6) -> ui6"),
        "app should be able to emit bit reversal code");
    assertTrue(
        mlirCode.contains(
            "%Imm6 = coredsl.cast %TREENAIL_WAS_HERE_reversed_0 : ui6 to ui6"),
        "app should be able to retain the original reversed encoding field "
            + "name");

    assertTrue(
        mlirCode.contains("%TREENAIL_WAS_HERE_reversed_1 = coredsl.bitextract "
                          + "%TREENAIL_WAS_HERE_rs1_2_0[0:2] : (ui3) -> ui3"),
        "app should be able to emit bit reversal code");
    assertTrue(mlirCode.contains("%TREENAIL_WAS_HERE_2 = coredsl.concat "
                                 + "%TREENAIL_WAS_HERE_rs1_4_3, "
                                 + "%TREENAIL_WAS_HERE_reversed_1 : ui2, ui3"),
               "app should be able to concat split and reversed bitfields");
    assertTrue(mlirCode.contains(
                   "%rs1 = coredsl.cast %TREENAIL_WAS_HERE_2 : ui5 to ui5"),
               "app should be able to retain the original split and reversed "
                   + "encoding field name");
  }

  @Test
  void constVolatileWorks() {
    var appInst = App.getInstance();
    var fileName = getClass().getResource("const_volatile.core_desc").getPath();
    var content = appInst.parse(fileName);
    var mlirCode = appInst.generateMLIR(content);
    assertNotNull(mlirCode, "MLIR should be output without errors");
    // Test register files with qualifiers
    assertTrue(mlirCode.contains("coredsl.register core_x @X[32] : ui32"));
    assertTrue(mlirCode.contains(
        "coredsl.register local const @CONST_REG_FILE[10] : ui32"));
    assertTrue(mlirCode.contains(
        "coredsl.register local volatile @VOLATILE_REG_FILE[12] : ui32"));
    assertTrue(mlirCode.contains("coredsl.register local const volatile "
                                 + "@CONST_VOLATILE_REG_FILE[14] : ui32"));
    // test scalar registers with qualifiers
    assertTrue(
        mlirCode.contains("coredsl.register local @NORMAL_REG = 5 : ui32"));
    assertTrue(mlirCode.contains(
        "coredsl.register local const @CONST_REG = 10 : ui32"));
    assertTrue(mlirCode.contains(
        "coredsl.register local volatile @VOLATILE_REG = 12 : ui32"));
    assertTrue(mlirCode.contains("coredsl.register local const volatile "
                                 + "@CONST_VOLATILE_REG = 42 : ui32"));
    // Make sure output MLIR contains address space command with qualifiers
    assertTrue(
        mlirCode.contains("coredsl.addrspace core_mem @MEM : (ui32) -> ui8"));
    assertTrue(mlirCode.contains(
        "coredsl.addrspace core_mem const @CONST_MEM : (ui64) -> ui8"));
    assertTrue(mlirCode.contains(
        "coredsl.addrspace core_mem volatile @VOLATILE_MEM : (ui8) -> ui8"));
    assertTrue(mlirCode.contains("coredsl.addrspace core_mem const volatile "
                                 + "@CONST_VOLATILE_MEM : (ui16) -> ui8"));

    assertTrue(mlirCode.contains("coredsl.alias @FIRST_MEM_VAL = @MEM[0]"));
    assertTrue(mlirCode.contains(
        "coredsl.alias const @FIRST_CONST_MEM_VAL = @CONST_MEM[0]"));
    assertTrue(mlirCode.contains(
        "coredsl.alias volatile @FIRST_VOLATILE_MEM_VAL = @VOLATILE_MEM[0]"));
    assertTrue(mlirCode.contains(
        "coredsl.alias const volatile @FIRST_CONST_VOLATILE_MEM_VAL = "
        + "@CONST_VOLATILE_MEM[0]"));
  }

  @Test
  void multipleDeclaratorsWork() {
    var appInst = App.getInstance();
    // NOTE: This file is parsed and converted to mlir in other tests
    var expectedFileName =
        getClass().getResource("intro_syntax.core_desc").getPath();
    var expectedContent = appInst.parse(expectedFileName);
    assertNotNull(expectedContent,
                  "app should be able to parse a simple CoreDSL file");
    var expectedMlir = appInst.generateMLIR(expectedContent);
    assertNotNull(expectedMlir);

    var testFileName =
        getClass()
            .getResource("intro_syntax_multiple_declarators.core_desc")
            .getPath();
    var testContent = appInst.parse(testFileName);
    assertNotNull(testContent);
    var gotMlir = appInst.generateMLIR(testContent);
    assertNotNull(gotMlir);

    assertEquals(gotMlir, expectedMlir);
  }

  @Test
  void shortCircuitEvaluationWorks() {
    var appInst = App.getInstance();
    var fileName = getClass().getResource("short_circuit.core_desc").getPath();
    var content = appInst.parse(fileName);
    var mlirCode = appInst.generateMLIR(content);
    assertNotNull(mlirCode);
    // clang-format off
    assertTrue(mlirCode.contains("""
          %7 = coredsl.cast %4 : ui1 to i1
          %6 = scf.if %7 -> (ui1) {
            %8 = hwarith.constant 10 : ui4
            %10 = hwarith.icmp lt %2, %8 : ui32, ui4
            %9 = hwarith.cast %10 : (i1) -> ui1
            scf.yield %9 : ui1
          } else {
            %8 = hwarith.constant 0 : ui1
            scf.yield %8 : ui1
          }\
      """));
    assertTrue(mlirCode.contains("""
          %7 = coredsl.cast %4 : ui1 to i1
          %6 = scf.if %7 -> (ui1) {
            %8 = hwarith.constant 1 : ui1
            scf.yield %8 : ui1
          } else {
            %8 = hwarith.constant 10 : ui4
            %10 = hwarith.icmp gt %2, %8 : ui32, ui4
            %9 = hwarith.cast %10 : (i1) -> ui1
            scf.yield %9 : ui1
          }\
      """));
    assertTrue(mlirCode.contains("""
          %4 = hwarith.constant 0 : ui32
          %5 = hwarith.icmp ne %0 %4
          %6 = coredsl.cast %5 : ui1 to i1
          %3 = scf.if %6 -> (ui1) {
            %7 = hwarith.constant 1 : ui1
            scf.yield %7 : ui1
          } else {
            %7 = hwarith.constant 0 : ui32
            %8 = hwarith.icmp ne %2 %7
            scf.yield %8 : ui1
          }\
      """));
    assertTrue(mlirCode.contains("""
          %7 = coredsl.cast %4 : ui1 to i1
          %6 = scf.if %7 -> (ui1) {
            %8 = hwarith.constant 10 : ui4
            %10 = hwarith.icmp lt %0, %8 : ui32, ui4
            %9 = hwarith.cast %10 : (i1) -> ui1
            scf.yield %9 : ui1
          } else {
            %8 = hwarith.constant 0 : ui1
            scf.yield %8 : ui1
          }
          %9 = coredsl.cast %6 : ui1 to i1
          %8 = scf.if %9 -> (ui1) {
            %10 = hwarith.constant 1 : ui1
            scf.yield %10 : ui1
          } else {
            %10 = hwarith.constant 10 : ui4
            %12 = hwarith.icmp gt %2, %10 : ui32, ui4
            %11 = hwarith.cast %12 : (i1) -> ui1
            %14 = coredsl.cast %11 : ui1 to i1
            %13 = scf.if %14 -> (ui1) {
              %15 = hwarith.constant 15 : ui4
              %17 = hwarith.icmp lt %2, %15 : ui32, ui4
              %16 = hwarith.cast %17 : (i1) -> ui1
              scf.yield %16 : ui1
            } else {
              %15 = hwarith.constant 0 : ui1
              scf.yield %15 : ui1
            }
            %16 = coredsl.cast %13 : ui1 to i1
            %15 = scf.if %16 -> (ui1) {
              %17 = hwarith.constant 1 : ui1
              scf.yield %17 : ui1
            } else {
              %17 = hwarith.constant 0 : ui1
              %19 = hwarith.icmp eq %2, %17 : ui32, ui1
              %18 = hwarith.cast %19 : (i1) -> ui1
              scf.yield %18 : ui1
            }
            scf.yield %15 : ui1
          }\
      """));
    assertTrue(mlirCode.contains("""
          %0 = hwarith.constant 0 : ui32
          %1 = hwarith.constant 0 : ui1
          %2 = coredsl.cast %1 : ui1 to ui32
          %3 = scf.while (%3 = %2) : (ui32) -> (ui32) {
            %4 = hwarith.constant 10 : ui4
            %6 = hwarith.icmp lt %3, %4 : ui32, ui4
            %5 = hwarith.cast %6 : (i1) -> ui1
            %8 = coredsl.cast %5 : ui1 to i1
            %7 = scf.if %8 -> (ui1) {
              %9 = coredsl.get @X[1] : ui32
              %10 = hwarith.constant 1 : ui1
              %11 = hwarith.add %9, %10 : (ui32, ui1) -> ui33
              %12 = coredsl.cast %11 : ui33 to ui32
              coredsl.set @X[1] = %12 : ui32
              %13 = hwarith.constant 10 : ui4
              %15 = hwarith.icmp lt %9, %13 : ui32, ui4
              %14 = hwarith.cast %15 : (i1) -> ui1
              scf.yield %14 : ui1
            } else {
              %9 = hwarith.constant 0 : ui1
              scf.yield %9 : ui1
            }
            %9 = coredsl.cast %7 : ui1 to i1
            scf.condition(%9) %3 : ui32
          } do {
          ^bb0(%3: ui32):
            %4 = hwarith.constant 2 : ui2
            %5 = coredsl.get @X[1] : ui32
            %6 = hwarith.add %5, %4 : (ui32, ui2) -> ui33
            %7 = coredsl.cast %6 : ui33 to ui32
            coredsl.set @X[1] = %7 : ui32
            %8 = hwarith.constant 1 : ui1
            %9 = hwarith.add %3, %8 : (ui32, ui1) -> ui33
            %10 = coredsl.cast %9 : ui33 to ui32
            scf.yield %10 : ui32
          }
          coredsl.set @X[2] = %3 : ui32\
      """));
    // clang-format on
  }

  void nestedLValuesTest() {
    var appInst = App.getInstance();
    var fileName =
            getClass().getResource("nested_lvalues.core_desc").getPath();
    var content = appInst.parse(fileName);
    assertNotNull(content,
            "app should be able to parse a simple CoreDSL file");
    var mlirCode = appInst.generateMLIR(content);
    assertNotNull(mlirCode);
    assertTrue(mlirCode.contains(
            "    %0 = hwarith.constant 100 : ui7\n" +
            "    %1 = coredsl.get @X[%rs2 : ui5] : ui32\n" +
            "    %2 = coredsl.cast %0 : ui7 to ui11\n" +
            "    %3 = coredsl.bitset %1[0:10] = %2 : (ui32, ui11) -> ui32\n" +
            "    coredsl.set @X[%rs2 : ui5] = %3 : ui32\n"));
    assertTrue(mlirCode.contains(
            "    %0 = hwarith.constant 8 : ui4\n" +
            "    %1 = coredsl.cast %rs2 : ui5 to ui32\n" +
            "    %2 = coredsl.get @MEM[%1 : ui32] : ui8\n" +
            "    %3 = coredsl.cast %0 : ui4 to ui5\n" +
            "    %4 = coredsl.bitset %2[0:4] = %3 : (ui8, ui5) -> ui8\n" +
            "    coredsl.set @MEM[%1 : ui32] = %4 : ui8\n"));
    assertTrue(mlirCode.contains(
            "    %0 = hwarith.constant 42 : ui6\n" +
            "    %1 = coredsl.get @PC : ui32\n" +
            "    %2 = coredsl.bitextract %1[16:0] : (ui32) -> ui17\n" +
            "    %3 = coredsl.cast %0 : ui6 to ui9\n" +
            "    %4 = coredsl.bitset %2[8:0] = %3 : (ui17, ui9) -> ui17\n" +
            "    %5 = coresdl.bitset %1[16:0] = %4 : (ui32, ui17) -> ui32\n" +
            "    coredsl.set @PC = %5 : ui32\n"));
  }
}
